application: 7drl01
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /update
  script: update.py
  login: admin

- url: /.*
  script: app.py
